### PR TITLE
Don't require Yarn to build the package on "postinstall"

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by dadaphl** [comment]
is there a reason to change that?

**Comment by davidyuk** [comment]
@dadaphl  Yes, check this log:
https://ci.aepps.com/blue/organizations/jenkins/aepp-identity/detail/PR-156/1/pipeline/#step-16-log-110

**Comment by dadaphl** [comment]
we could also add yarn to the build image

**Comment by davidyuk** [comment]
Or to `devDependencies` of this package, you think it is a better solution?
Dependency on `yarn` can be not so obvious for somebody who will decide to use this package from git repository. Actually, `yarn` is not needed in this case, because it just runs `build` script. `npm` can do the same, and it usually included with node.

**Comment by outergod** [comment]
Next time, please consider just adding Yarn to your build image. Even the official upstream `node` Docker image contains it. I'm incorporating your change (after amendments) this time to facilitate progress.

**Pull request merged**
